version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ppt_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - ppt_network

  app:
    build: .
    container_name: ppt_app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/health').read()"]
      interval: 5s
      timeout: 3s
      retries: 12
    environment:
      - REDIS_URL=redis://redis:6379
      - PPT_STORAGE_PATH=/app/ppt_files
    env_file:
      - .env
    volumes:
      - ./ppt_files:/app/ppt_files
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ppt_network

  # nginx service removed per request; Streamlit at 8501 is the primary UI

  streamlit:
    build: .
    container_name: ppt_streamlit
    command: [
      "streamlit", "run", "frontend/app.py",
      "--server.port", "8501",
      "--server.address", "0.0.0.0",
      "--server.enableCORS", "false",
      "--browser.gatherUsageStats", "false"
    ]
    environment:
      - API_BASE_URL=http://app:8000
    ports:
      - "8501:8501"
    depends_on:
      app:
        condition: service_healthy
    networks:
      - ppt_network

networks:
  ppt_network:
    driver: bridge
